# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mvvm+rac' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mvvm+rac
  pod 'Masonry'
  pod 'ReactiveObjC'
  pod 'YYKit'

end
